Repository WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-externatic, pull requests merged in 2024-09, with the labels that each got.

#6 Us 02 form announce
  client/package.json
  client/src/App.jsx
  client/src/components/FormAnnounce.jsx
  client/src/main.jsx
  client/src/pages/AddAnnounce.jsx
  client/src/services/announceEditAction.js
  client/src/services/announceIdLoader.js
  client/src/services/companyLoader.js
  package-lock.json
  server/app/controllers/AnnounceActions.js
  server/database/models/CompanyRepository.js
Labels: CORRECTIONS DONE, REVIEWED

#5 Us 03 announce page
  client/src/components/AnnounceCard.jsx
  client/src/main.jsx
  client/src/pages/Announce.jsx
  client/src/services/announceLoader.js
Labels: REVIEWED

#7 Us06 01 home page
  client/src/App.jsx
  client/src/assets/images/Header_People_Externatech.png
  client/src/assets/images/HomePage_soulignement_vous.png
  client/src/assets/images/Line_green_confiance.png
  client/src/assets/images/Logo_externatech.png
  client/src/assets/images/Wave_grey.png
  client/src/assets/images/background.webp
  client/src/assets/images/header_without_picture.png
  client/src/assets/styles/App.css
  client/src/assets/styles/Homepage.css
  client/src/main.jsx
  client/src/pages/HomePage.jsx
Labels: CORRECTIONS DONE, REVIEWED

#9 :sparkles: CSS and layout of EditAnnounce
  client/src/assets/images/wave_top.png
  client/src/assets/styles/App.css
  client/src/assets/styles/EditAnnounce.css
  client/src/pages/EditAnnounce.jsx
Labels: REVIEW REQUESTED, REVIEWED

#8 Announce Detail
  client/src/components/AnnounceCard.jsx
  client/src/main.jsx
  client/src/pages/AnnounceDetail.jsx
  client/src/services/announceIdLoader.js
  client/src/services/announceLoader.js
  client/src/services/companyLoader.js
Labels: REVIEWED

#10 Us10 component announce form
  client/index.html
  client/src/assets/styles/EditAnnounce.css
  client/src/components/FormAnnounce.jsx
  client/src/pages/AddAnnounce.jsx
  client/src/pages/EditAnnounce.jsx
  client/src/services/announceEditAction.js
Labels: REVIEW REQUESTED, REVIEWED

#11 Us 08 nav bar
  client/src/App.jsx
  client/src/assets/images/Logo.png
  client/src/assets/styles/App.css
  client/src/assets/styles/Navbar.css
  client/src/components/FormAnnounce.jsx
  client/src/components/NavBar.jsx
  client/src/main.jsx
  client/src/pages/AddAnnounce.jsx
  server/app/controllers/AnnounceActions.js
  server/database/models/AnnounceRepository.js
  server/database/models/CompanyRepository.js
Labels: REVIEWED

#12 Us07 carrousel
  client/package.json
  client/src/App.jsx
  client/src/assets/styles/App.css
  client/src/assets/styles/CardCompany.css
  client/src/assets/styles/CarrouselCompanyHomePage.css
  client/src/assets/styles/Homepage.css
  client/src/components/CardCompany.jsx
  client/src/components/CarrouselCompanyHomePage.jsx
  client/src/main.jsx
  client/src/pages/HomePage.jsx
  package-lock.json
Labels: REVIEWED

#13 Us 09 footer
  client/src/App.jsx
  client/src/assets/images/facebook.svg
  client/src/assets/images/instagram.svg
  client/src/assets/images/linkedin.svg
  client/src/assets/images/twitter.svg
  client/src/assets/styles/App.css
  client/src/assets/styles/Footer.css
  client/src/assets/styles/Homepage.css
  client/src/assets/styles/LegalPages.css
  client/src/assets/styles/Navbar.css
  client/src/components/Footer.jsx
  client/src/components/NavBar.jsx
  client/src/main.jsx
  client/src/pages/Footer/Cgu.jsx
  client/src/pages/Footer/Charter.jsx
  client/src/pages/Footer/Confidential.jsx
  client/src/pages/Footer/CookiesPolicy.jsx
  client/src/pages/Footer/Legal.jsx
Labels: REVIEWED

#14 Us13 add image and logo company
  client/src/assets/styles/CardCompany.css
  client/src/components/CardCompany.jsx
  server/app/config.js
  server/app/router.js
  server/app/services/upload.js
  server/database/models/CompanyRepository.js
  server/database/schema.sql
  server/package.json
  server/public/assets/images/default.png
  server/public/assets/images/logo_default.png
Labels: REVIEWED

#16 Us 15 create table candidate
  server/app/controllers/CandidateActions.js
  server/app/router.js
  server/database/models/CandidateRepository.js
  server/database/models/CompanyRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: CORRECTIONS DONE, REVIEW REQUESTED

#15 Us17 partener company
  client/src/App.jsx
  client/src/assets/images/Company_AFAC.png
  client/src/assets/images/Company_Nodas.png
  client/src/assets/images/Company_Original_digitals.png
  client/src/assets/images/Company_SAH.png
  client/src/assets/images/Company_nam_nam.png
  client/src/assets/styles/CorporateSponcor.css
  client/src/assets/styles/Homepage.css
  client/src/components/CorporateSponcor.jsx
  client/src/pages/HomePage.jsx
Labels: REVIEW REQUESTED, REVIEWED

#18 Us 12 building announce detail components and css
  client/src/App.jsx
  client/src/assets/images/photoentreprise23.png
  client/src/assets/styles/AnnounceDetail.css
  client/src/components/AnnounceCard.jsx
  client/src/components/AnnounceDetailCompanyDescription.jsx
  client/src/components/AnnounceDetailCompanyMore.jsx
  client/src/components/AnnounceDetailTitle.jsx
  client/src/components/AnnouncePostDetail.jsx
  client/src/components/FormAnnounce.jsx
  client/src/components/NavBar.jsx
  client/src/pages/AddAnnounce.jsx
  client/src/pages/Announce.jsx
  client/src/pages/AnnounceDetail.jsx
  client/src/services/announceLoader.js
Labels: REVIEWED

#19 Us 11 created filter announce
  client/src/components/AnnounceCard.jsx
  client/src/components/AnnounceDetailCard.jsx
  client/src/main.jsx
  client/src/pages/Announce.jsx
  client/src/services/announceEditAction.js
  client/src/services/announceLoader.js
  server/app/controllers/AnnounceActions.js
  server/app/controllers/ContractActions.js
  server/app/router.js
  server/database/models/AnnounceRepository.js
  server/database/models/ContractRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEW REQUESTED, REVIEWED

#20 Us16 register candidat front
  client/src/App.jsx
  client/src/assets/styles/EditAnnounce.css
  client/src/assets/styles/Homepage.css
  client/src/assets/styles/RegisterCandidat.css
  client/src/components/FormCandidat.jsx
  client/src/main.jsx
  client/src/pages/Announce.jsx
  client/src/pages/HomePage.jsx
  client/src/pages/RegisterCandidat.jsx
  client/src/services/candidateAction.js
  server/app/controllers/CandidateActions.js
  server/database/models/CandidateRepository.js
  server/database/schema.sql
  server/public/uploads/.gitkeep
Labels: REVIEWED

#21 Us20 answer announce backend
  server/app/controllers/AnswerActions.js
  server/app/router.js
  server/database/models/AnswerRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#22 Us 19 login candidate
  server/app/config.js
  server/app/controllers/CandidateActions.js
  server/app/router.js
  server/app/services/candidateAuth.js
  server/database/models/CandidateRepository.js
  server/database/schema.sql
  server/package.json
Labels: REVIEWED

#23 Us 18 login company
  server/app/controllers/CompanyActions.js
  server/app/router.js
  server/app/services/auth.js
  server/app/services/companyAuth.js
  server/database/models/CompanyRepository.js
Labels: REVIEW REQUESTED

#24 login client and create file login-company
  client/src/main.jsx
  client/src/pages/LoginCompany.jsx
  client/src/services/companyAction.js
  server/app/router.js
  server/app/services/companyAuth.js
Labels: REVIEWED

#25 Us23 edit profile
  client/src/assets/images/default.png
  client/src/assets/images/favicon.png
  client/src/assets/images/logo_default.png
  client/src/assets/styles/RegisterCandidat.css
  client/src/components/CardCompany.jsx
  client/src/components/FormCandidat.jsx
  client/src/components/FormCompany.jsx
  client/src/main.jsx
  client/src/pages/EditCandidate.jsx
  client/src/pages/EditCompany.jsx
  client/src/pages/RegisterCandidat.jsx
  client/src/pages/RegisterCompany.jsx
  client/src/services/announceLoader.js
  client/src/services/candidateAction.js
  client/src/services/candidateLoader.js
  client/src/services/companyAction.js
  client/src/services/companyLoader.js
  server/app/controllers/CandidateActions.js
  server/app/controllers/CompanyActions.js
  server/app/router.js
  server/app/services/candidateAuth.js
  server/app/services/companyAuth.js
  server/app/services/upload.js
  server/database/models/CandidateRepository.js
  server/database/models/CompanyRepository.js
Labels: REVIEWED

#26 Us19 02 create login
  client/src/App.jsx
  client/src/components/FormCandidat.jsx
  client/src/components/NavBar.jsx
  client/src/context/AuthentificationContext.jsx
  client/src/main.jsx
  client/src/pages/Forbidden.jsx
  client/src/pages/HomePage.jsx
  client/src/pages/LoginCandidate.jsx
  client/src/services/request.js
  server/app/controllers/CandidateActions.js
  server/app/router.js
  server/app/services/candidateAuth.js
Labels: REVIEWED

#27 add css announce
  client/src/App.jsx
  client/src/assets/styles/announce.css
  client/src/components/AnnounceCard.jsx
  client/src/components/AnnounceDetailCard.jsx
  client/src/components/CarrouselCompanyHomePage.jsx
  client/src/pages/Announce.jsx
  client/src/pages/LoginCompany.jsx
  client/src/pages/RegisterCompany.jsx
  client/src/services/announceEditAction.js
  client/src/services/announceLoader.js
  server/app/controllers/AnnounceActions.js
  server/app/controllers/ContractActions.js
  server/app/router.js
  server/app/services/companyAuth.js
  server/database/models/AnnounceRepository.js
  server/database/models/CompanyRepository.js
  server/database/models/ContractRepository.js
Labels: REVIEWED

#29 Us21 company announce
  client/src/App.jsx
  client/src/assets/styles/AnnounceByCompany.css
  client/src/main.jsx
  client/src/pages/CompanyAnnounce.jsx
  client/src/services/announceLoader.js
  package-lock.json
  server/app/controllers/AnnounceActions.js
  server/app/router.js
  server/database/models/AnnounceRepository.js
  server/tests/announce/repository.spec.js
  server/tests/announce/route.spec.js
Labels: REVIEWED

#33 :sparkles: add candidate on client and server , and build response
  client/src/components/AnnounceDetailTitle.jsx
  server/app/controllers/AnswerActions.js
  server/database/models/AnswerRepository.js
  server/public/uploads/3f2e0638-d3d0-4bf6-baa4-47f42af6ad71.png
  server/public/uploads/69860ee9-a703-4fd7-a7dd-d1bbc14d6f5a.png
  server/public/uploads/aa58ae25-ecdc-4424-9ad6-d102189c153e.png
  server/public/uploads/e6097f0c-27a5-4088-ba38-91ff53f44d87.png
Labels: REVIEWED

#34 :bug: path login candidate in navBar
  client/src/components/NavBar.jsx
Labels: REVIEWED

#35 Us33 company-experience
  client/src/assets/styles/AnnounceByCompany.css
  client/src/components/AnnounceCard.jsx
  client/src/context/AuthContext.jsx
  client/src/main.jsx
  client/src/pages/CompanyAnnounce.jsx
  client/src/pages/HomePage.jsx
  client/src/services/announceEditAction.js
  client/src/services/announceLoader.js
  server/app/controllers/AnnounceActions.js
  server/app/router.js
  server/app/services/companyAuth.js
  server/app/services/middleware.js
  server/database/models/AnnounceRepository.js
  server/database/schema.sql
Labels: REVIEWED

#36 Us 24 see answer announce
  client/src/App.jsx
  client/src/assets/styles/AnswerCandidate.css
  client/src/components/AnswerCandidate.jsx
  client/src/components/MyAnswers.jsx
  client/src/components/NavBar.jsx
  client/src/main.jsx
  client/src/pages/AnswerCandidate.jsx
  client/src/pages/LoginCandidate.jsx
  client/src/pages/LoginCompany.jsx
  client/src/services/announceLoader.js
  client/src/services/candidateLoader.js
  server/app/controllers/AnswerActions.js
  server/app/router.js
  server/app/services/candidateAuth.js
  server/database/models/AnnounceRepository.js
  server/database/models/AnswerRepository.js
Labels: REVIEWED

#38 Us101 moove contract info from
  client/src/assets/styles/AnnounceDetail.css
  client/src/components/AnnounceDetailCard.jsx
  client/src/components/AnnounceDetailCompanyMore.jsx
  client/src/components/AnnounceDetailTitle.jsx
  client/src/components/AnswerCandidate.jsx
  client/src/components/FormCandidat.jsx
  client/src/main.jsx
  client/src/pages/AnnounceDetail.jsx
  client/src/pages/CompanyAnnounce.jsx
  server/app/controllers/AnnounceActions.js
  server/app/router.js
  server/database/models/AnnounceRepository.js
Labels: REVIEWED

#37 fixed bug and link
  client/src/assets/styles/announce.css
  client/src/components/AnnounceCard.jsx
  client/src/components/AnnounceDetailCompanyDescription.jsx
  client/src/components/AnnounceDetailCompanyMore.jsx
  client/src/components/AnnounceDetailTitle.jsx
  client/src/components/AnnouncePostDetail.jsx
  client/src/components/CardCompany.jsx
  client/src/components/Footer.jsx
  client/src/components/NavBar.jsx
  client/src/context/AuthContext.jsx
  client/src/pages/Announce.jsx
  client/src/pages/Footer/Legal.jsx
  client/src/pages/LoginCandidate.jsx
  client/src/pages/LoginCompany.jsx
  server/app/controllers/CompanyActions.js
Labels: REVIEWED

#39 Us38 company experience
  client/src/assets/styles/Homepage.css
  client/src/assets/styles/Login.css
  client/src/components/AnnounceCard.jsx
  client/src/components/AnnounceDetailTitle.jsx
  client/src/components/Footer.jsx
  client/src/components/NavBar.jsx
  client/src/main.jsx
  client/src/pages/CompanyAnnounce.jsx
  client/src/pages/EditCandidate.jsx
  client/src/pages/HomePage.jsx
  client/src/pages/LoginCandidate.jsx
  server/app/controllers/AnnounceActions.js
Labels: REVIEWED

#40 fixed bug and image dinamique on announce card
  client/src/assets/styles/announce.css
  client/src/components/AnnounceCard.jsx
  server/database/models/AnnounceRepository.js
Labels: REVIEWED

#41 Us 102 data implement
  server/database/schema.sql
Labels: REVIEWED

#42 Us37 user experience
  client/src/components/AnnounceDetailCompanyMore.jsx
  client/src/components/Footer.jsx
  client/src/pages/HomePage.jsx
Labels: REVIEWED

#43 Us 34 see answer candidate
  client/src/components/AnnounceCard.jsx
  client/src/main.jsx
  client/src/pages/AnswerCompany.jsx
  client/src/services/companyLoader.js
  server/app/controllers/AnswerActions.js
  server/app/controllers/CandidateActions.js
  server/app/router.js
  server/database/models/AnswerRepository.js
  server/database/models/CandidateRepository.js
  server/public/uploads/3f2e0638-d3d0-4bf6-baa4-47f42af6ad71.png
  server/public/uploads/69860ee9-a703-4fd7-a7dd-d1bbc14d6f5a.png
  server/public/uploads/aa58ae25-ecdc-4424-9ad6-d102189c153e.png
  server/public/uploads/e6097f0c-27a5-4088-ba38-91ff53f44d87.png
Labels: REVIEWED

#44 fixed bug on announce css and announce card
  client/src/assets/styles/announce.css
  client/src/components/AnnounceCard.jsx
Labels: REVIEWED

#45 Us 103 description company back and front
  client/src/components/AnnounceDetailCompanyDescription.jsx
  server/database/models/AnnounceRepository.js
  server/database/schema.sql
Labels: REVIEWED

#46 Us39 answer candidature
  client/src/assets/styles/AnnounceDetail.css
  client/src/assets/styles/AnswerCandidate.css
  client/src/components/MyAnswers.jsx
  client/src/main.jsx
  client/src/pages/AnswerCandidate.jsx
  client/src/pages/AnswerCompany.jsx
  client/src/services/answerAction.js
  server/app/controllers/AnswerActions.js
  server/app/router.js
  server/database/models/AnswerRepository.js
  server/database/models/CandidateRepository.js
  server/database/schema.sql
Labels: REVIEWED

#47 Us40 patch interface
  client/src/assets/styles/Homepage.css
  client/src/components/AnnounceCard.jsx
  client/src/components/CardCompany.jsx
  client/src/components/Footer.jsx
  client/src/pages/HomePage.jsx
  server/app/controllers/AnswerActions.js
  server/database/models/AnnounceRepository.js
Labels: REVIEW REQUESTED, REVIEWED

#48 Us 34 see answer candidate
  client/src/App.jsx
  client/src/assets/styles/AnswerCompany.css
  client/src/pages/AnswerCompany.jsx
  client/src/services/companyLoader.js
  server/app/controllers/CandidateActions.js
Labels: REVIEWED
